spring:
  cloud:
    gateway:
      routes:
        - id: profilesPrincipal
          uri: http://profiles
          predicates:
            - Path=/api/v1/linkedin, /api/v1/linkedin/**, /api/v1/profiles/active/me/*, /api/v1/profiles/me/accounts, /api/v1/profiles/me/linkedin, /api/v1/account, /api/v1/account/**, /api/v1/profiles/me, /api/v1/profiles/me/**, /api/v1/webhook/oneflow, /api/v1/oneflow/create, /api/v1/profiles/*, /api/v1/profiles, /api/v1/resumes, /api/v1/cover-letter, /api/v1/interview-review, /api/v1/interview-review-status, /api/v1/fetch-file-content, /api/v1/add-gig-overview, /api/v1/job-matching/**, /api/v1/add-user-overview/**, /api/v1/user-matching, /api/v1/add-users-overview, /api/v1/matching-wages, /api/v1/save-interview-review, /api/v1/website-visit, /api/v1/webhook/linkedin-messages, /api/v1/consultant-visit, /api/v1/notes/search, /api/v1/get-suitable-users/**, /api/v1/gig-matching, /api/v1/get-suitable-gigs/**, /api/v1/user-matching-wages, /api/v1/get-recent-consultants, /api/v1/contact-us-message, /api/v1/bullet-points-cv, /api/v1/add-agency-user, /api/v1/get-agencies-names, /api/v1/knowledge-program/access/requests, /api/v1/knowledge-program/access/*/close, /api/v1/knowledge-program/request, /api/v1/add-agency-admin, /api/v1/agencies-by-name, /api/v1/consultant-visit/report, /api/v1/agency-profiles-upload, /api/v1/get-gig/**, /api/v1/get-gig-suggestions/**, /api/v1/trueoriginal/isCertified, /api/v1/trueoriginal/certificates, /api/v1/profiles/me/personalized-articles, /api/v1/content/search,  /api/v1/webhook/mutate-publication,  /api/v1/webhook/mutate-gig,  /api/v1/webhook/mutate-webinar,  /api/v1/webhook/mutate-blog-post,  /api/v1/webhook/mutate-future-study, /api/v1/get-cv-data/*, /api/v1/*/update-cv-data, /api/v1/publication/*, /api/v1/skills/approve, /api/v1/gig-categories, /api/v1/rate-gig, /api/v1/publication/*/update-views, /api/v1/publication/*/update-saves, /api/v1/remove-gig-information, /api/v1/general-dashboard-information, /api/v1/average-characteristics, /api/v1/gender-balance, /api/v1/age-statistics, /api/v1/profiles/favorite-consultants/*, /api/v1/profiles/favorite-gigs/*, /api/v1/rate-consultant, /api/v1/agencies-managers, /api/v1/name-search, /api/v1/users-count, /api/v1/department-profile, /api/v1/department-profiles-upload, /api/v1/positions, /api/v1/positions/**, /api/v1/positions/*/matched-employees, /api/v1/positions/*/matched-employees/*, /api/v1/positions/matched-employees, /api/v1/positions/description, /api/v1/employees/*/skills, /api/v1/employees/*/personal-details, /api/v1/employees/dynamic-search, /api/v1/department, /api/v1/roles, /api/v1/positions/archived, /api/v1/matches, /api/v1/matches/**, /api/v1/matches/matched-employees, /api/v1/profiles/average-profile-percentage, /api/v1/projects
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: postsPrincipal
          uri: http://profiles
          predicates:
            - Path=/api/v1/favorite-gigs, /api/v1/favorite-gigs/**, /api/v1/favorite-consultants,/api/v1/favorite-consultants/**, /api/v1/posts, /api/v1/posts/**, /api/v1/posts-likes, /api/v1/posts-likes/**, /api/v1/posts-comments, /api/v1/posts-comments/**, /api/v1/posts/me, /api/v1/posts/comments/me, /api/v1/posts/likes/me, /api/v1/comments/likes/me, /api/v1/comment-likes, /api/v1/comment-likes/**
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: PublicSearch
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles, /api/v1/profiles/search
            - Query=projection, public-search-profile
            - Query=isOpenForWork, true
        - id: AdminSearch
          uri: http://api-gateway
          predicates:
            - Path=/api/v1/profiles, /api/v1/profiles/*
            - Query=projection, admin-search-profile
            - Method=GET
          filters:
            - RewritePath=/api/v1/(?<path>.*), /api/v1/admin//$\{path}
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/*/*, /api/v1/description/**, /api/v1/profiles/api-doc, /api/v1/profile/profiles, /api/v1/experiences/**, /api/v1/skills/**, /api/v1/languages/**, /api/v1/read-later/**
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
        - id: adminSearchDownstream
          uri: http://profiles
          predicates:
            - Path=/api/v1/admin/**
          metadata:
            auth-roles:
              - iamai-admin
          filters:
            - RewritePath=/api/v1/admin/(?<path>.*), /api/v1//$\{path}
        - id: GroupsUsers
          uri: http://profiles
          predicates:
            - Path= /api/v1/link/preview, /api/v1/groups-posts-comments-reply-likes, /api/v1/groups-posts-comments-reply-likes/**, /api/v1/groups-user, /api/v1/groups-user/**,  /api/v1/groups, /api/v1/groups/**, /api/v1/me/group/*/access, /api/v1/*/group/*/check-access, /api/v1/*/group/*/subscribe, /api/v1/*/group/*/unsubscribe, /api/v1/subscribe, /api/v1/unsubscribe,  /api/v1/group/access/*/approve, /api/v1/group/access/*/decline, /api/v1/group/access/requests, /api/v1/me/groups, /api/v1/group/add-users, /api/v1/group/**
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: GroupsPosts
          uri: http://profiles
          predicates:
            - Path=/api/v1/groups-posts, /api/v1/groups-posts/**, /api/v1/groups-posts-likes, /api/v1/groups-posts-likes/**, /api/v1/groups-posts-comments, /api/v1/groups-posts-comments/**, /api/v1/last-two-groups
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: GroupsPostsCommentsReply
          uri: http://profiles
          predicates:
            - Path=/api/v1/groups-posts-comments-likes, /api/v1/groups-posts-comments-likes/**, /api/v1/groups-posts-comments-reply, /api/v1/groups-posts-comments-reply/** 
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: UserGroupsPostsCommentsReply
          uri: http://profiles
          predicates:
            - Path=  /api/v1/group/users/*, /api/v1/me/request-consultant/*, /api/v1/me/post-gigs, /api/v1/group/posts/comments/me, /api/v1/group/posts/likes/me, /api/v1/group/posts/comments/likes/me, /api/v1/group/posts/comments/reply/me, /api/v1/last-two-posts, /api/v1/create-gig-ad
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: Subscription
          uri: http://profiles
          predicates:
            - Path=  /api/v1/newsletter/subscribe/me, /api/v1/newsletter/unsubscribe/me, /api/v1/newsletter-subscription/**, /api/v1/newsletter-subscription
            - Method=GET,POST
          filters:
            - AddPrincipalToPathFilter
keycloak-client:
  server-url: https://auth-dev.iamaiworld.ai/auth
