spring:
  cloud:
    gateway:
      routes:
        - id: profilesPrincipal
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/me, /api/v1/profiles/me/**
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: PublicSearch
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles
            - Query=projection, public-search-profile
            - Query=isOpenForWork, true
        - id: AdminSearch
          uri: http://api-gateway
          predicates:
            - Path=/api/v1/profiles, /api/v1/profiles/*
            - Query=projection, admin-search-profile
            - Method=GET
          filters:
            - RewritePath=/api/v1/(?<path>.*), /api/v1/admin//$\{path}
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/*/*, /api/v1/description/**, /api/v1/profiles/api-doc, /api/v1/profile/profiles, /api/v1/experiences/**, /api/v1/skills/**, /api/v1/languages/**, /api/v1/read-later/**
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
        - id: adminSearchDownstream
          uri: http://profiles
          predicates:
            - Path=/api/v1/admin/**
          metadata:
            auth-roles:
              - iamai-admin
          filters:
            - RewritePath=/api/v1/admin/(?<path>.*), /api/v1//$\{path}
keycloak-client:
  server-url: https://auth-dev.iamai.se/auth
