spring:
  cloud:
    gateway:
      routes:
        - id: profilesPrincipal
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/active/me/*, /api/v1/profiles/me/accounts, /api/v1/account, /api/v1/account/**, /api/v1/profiles/me, /api/v1/profiles/me/**, /api/v1/webhook/oneflow, /api/v1/oneflow/create, /api/v1/profiles/*, /api/v1/profiles, /api/v1/resumes, /api/v1/cover-letter
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: postsPrincipal
          uri: http://profiles
          predicates:
            - Path=/api/v1/posts, /api/v1/posts/**, /api/v1/posts-likes, /api/v1/posts-likes/**, /api/v1/posts-comments, /api/v1/posts-comments/**, /api/v1/posts/me, /api/v1/posts/comments/me, /api/v1/posts/likes/me, /api/v1/comments/likes/me, /api/v1/comment-likes, /api/v1/comment-likes/**
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: PublicSearch
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles, /api/v1/profiles/search
            - Query=projection, public-search-profile
            - Query=isOpenForWork, true
        - id: AdminSearch
          uri: http://api-gateway
          predicates:
            - Path=/api/v1/profiles, /api/v1/profiles/*
            - Query=projection, admin-search-profile
            - Method=GET
          filters:
            - RewritePath=/api/v1/(?<path>.*), /api/v1/admin//$\{path}
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/*/*, /api/v1/description/**, /api/v1/profiles/api-doc, /api/v1/profile/profiles, /api/v1/experiences/**, /api/v1/skills/**, /api/v1/languages/**, /api/v1/read-later/**
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
        - id: adminSearchDownstream
          uri: http://profiles
          predicates:
            - Path=/api/v1/admin/**
          metadata:
            auth-roles:
              - iamai-admin
          filters:
            - RewritePath=/api/v1/admin/(?<path>.*), /api/v1//$\{path}
        - id: GroupsUsers
          uri: http://profiles
          predicates:
            - Path= /api/v1/link/preview, /api/v1/groups-posts-comments-reply-likes, /api/v1/groups-posts-comments-reply-likes/**, /api/v1/groups-user, /api/v1/groups-user/**,  /api/v1/groups, /api/v1/groups/**, /api/v1/me/group/*/access, /api/v1/me/group/*/check-access, /api/v1/me/group/*/subscribe, /api/v1/me/group/*/unsubscribe, /api/v1/subscribe, /api/v1/unsubscribe,  /api/v1/group/access/*/approve, /api/v1/group/access/*/decline, /api/v1/group/access/requests
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: GroupsPosts
          uri: http://profiles
          predicates:
            - Path=/api/v1/groups-posts, /api/v1/groups-posts/**, /api/v1/groups-posts-likes, /api/v1/groups-posts-likes/**, /api/v1/groups-posts-comments, /api/v1/groups-posts-comments/**
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: GroupsPostsCommentsReply
          uri: http://profiles
          predicates:
            - Path=/api/v1/groups-posts-comments-likes, /api/v1/groups-posts-comments-likes/**, /api/v1/groups-posts-comments-reply, /api/v1/groups-posts-comments-reply/** 
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: UserGroupsPostsCommentsReply
          uri: http://profiles
          predicates:
            - Path=  /api/v1/group/users/*, /api/v1/me/request-consultant/*, /api/v1/me/post-gigs, /api/v1/group/posts/comments/me, /api/v1/group/posts/likes/me, /api/v1/group/posts/comments/likes/me, /api/v1/group/posts/comments/reply/me
            - Method=GET,PUT,PATCH,DELETE,POST
          filters:
            - AddPrincipalToPathFilter
        - id: Subscription
          uri: http://profiles
          predicates:
            - Path=  /api/v1/newsletter/subscribe/me, /api/v1/newsletter/unsubscribe/me, /api/v1/newsletter-subscription/**, /api/v1/newsletter-subscription
            - Method=GET,POST
          filters:
            - AddPrincipalToPathFilter
keycloak-client:
  server-url: https://auth.iamai.se/auth
