spring.servlet.multipart.max-file-size: 1000MB
spring.servlet.multipart.max-request-size: 1000MB
server:
  forward-headers-strategy: framework
spring:
  main:
    allow-bean-definition-overriding: true
  data.rest.base-path: api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/ats-profiles?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          queries: true
          ehcache:
            missing_cache_strategy: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  mail:
    smtp:
      timeout: 60000
    host: smtp.mandrillapp.com
    port: 587
    username: IAMAI
    password: md-ZpxXER_k9MwK0S8_x55eNQ
    admin: gladiypavlo@gmail.com
    base-link: https://dev.iamai.se/user/
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc.api-docs.path: /api/v1/profiles/api-doc
logging:
  level:
    com.agenatech: DEBUG
health:
  config:
    enabled: false

server.servlet.encoding.charset: UTF-8
server.servlet.encoding.force-response: true
web.base-url: https://dev.iamai.se/
api.base-url: https://dev.iamai.se/api/v1
fileClient.url: https://api-dev.iamai.se
keycloak-client:
  server-url: https://auth-dev.iamai.se/auth
  realm: iamai
aws.accessKey: '{cipher}49ff9515bae71d0606ded65bbc8151fc22537eb3b6074e2ea535913aa0b8ca0f799e691668ac1b41cb752a99d9ba557d'
aws.secretKey: '{cipher}bf90b6127ae911113f1285fed824ba30c3a0f493982a996104d3a8b350aad0fe9ccbe7cf6089391090e6f1c48b97a53a0b2ba0479e427d279a863a04e97ec1ef'
mailchimp.Key: '{cipher}ef03af8b6d311dc45f2536a9d097a730fa1ab986444767cb3ceffe2433a3f615a7f5d0278d14dfe5bfb1a69ce1430b99284665b27b15f7e33e76460f304b3b9d'
pipedrive.Key: '{cipher}e086feb9e58268d5382c43bbd8051ddb9cf3e0fd1f529eefc6984fce400f12fa9966ec76ac6d4530c97f1c5e730f14c445c51277e284191cfdfa4de1b36620a0'
data.transfer.cron: '0 0 0 2 1 *'